apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: college-club-system
type: Opaque
data:
  # Base64 encoded 'postgresql://sec_user:SuperSecurePassword123!@db:5432/college_club_db'
  DATABASE_URL: cG9zdGdyZXNxbDovL3NlY191c2VyOlN1cGVyU2VjdXJlUGFzc3dvcmQxMjMhQGRiOjU0MzIvY29sbGVnZV9jbHViX2Ri
  # Base64 encoded 'prod_secret_key_12345'
  JWT_SECRET_KEY: cHJvZF9zZWNyZXRfa2V5XzEyMzQ1
